language: cpp

# We depend on revision numbering here
git:
  depth: false

# We release every commit, which creates tags, avoid building twice
if: tag IS blank

matrix:
  include:

 
  - os: linux
    # Important, as old GCC from brew is broken.
    name: "Windows build"
    dist: bionic
    addons:
      apt:
        update: true
        packages:
        - binutils-mingw-w64-i686
        - gcc-mingw-w64-i686
    script:
      # Preparatory actions
      - BUILD=$(($(git rev-list --count --first-parent HEAD)+3500))
      - echo "Build number ${BUILD}"
      - mkdir -p ciout
      # Disable compiler overrides as they cause problems
      - unset CC ; unset CXX ; unset CC_FOR_BUILD ; unset CXX_FOR_BUILD
      # homebrew addon is just broken; force update here
      - brew install yasm mingw-w64
      # Set compilers compatible with Windows
      - export CC=i686-w64-mingw32-gcc
      - export CXX=i686-w64-mingw32-g++
      - export LD=i686-w64-mingw32-ld
      - export AR=i686-w64-mingw32-ar
      - export RANLIB=i686-w64-mingw32-ranlib
      - export AS=i686-w64-mingw32-as
      # Build develop build
      - ./configure --cross=i686-w64-mingw32 || exit 1
      - make -j $(getconf _NPROCESSORS_ONLN) || exit 1
      - mv DerivedData/MinGW-i686/onscripter-ru.exe ciout ; cp -r Resources/Windows/dlls ciout/dlls ; cd ciout
      - zip -qry onscripter-ru_win_r${BUILD}_dev.zip onscripter-ru.exe dlls || exit 1
      - rm -rf onscripter-ru.exe dlls ; cd ..
      # Build release build
      - ./configure --cross=i686-w64-mingw32 --release-build --strip-binary || exit 1
      - make clean || exit 1
      - make -j $(getconf _NPROCESSORS_ONLN) || exit 1
      - mv DerivedData/MinGW-i686/onscripter-ru.exe ciout ; cp -r Resources/Windows/dlls ciout/dlls ; cd ciout
      - zip -qry onscripter-ru_win_r${BUILD}.zip onscripter-ru.exe dlls || exit 1
      - rm -rf onscripter-ru.exe dlls ; cd ..
